<?php
define("CONECTAR",0);
define("ENVIAR_RUTA",1);
define("REG_PLATAFORMA",2);
define("REG_RUTA",3);
define("REG_USUARIO",4);
define("PLATAFORMA_DISPONIBLE",5);
define("OCUPAR_PLATAFORMA",6);
define("VERIFICAR_CONEXION",7);
define("RUTA_PRUEBA",8);
define("SECTORES",9);
define("OBTENER_PLATAFORMA",10);
define("VERIFICAR_MENSAJE",11);
define("OBTENER_PETICION",12);
?>